name: GitHub Actions Hello World
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Hello-World:
    runs-on: ubuntu-latest
    steps:
     - name: checkout repo
       uses: actions/checkout@main
     - name: build hello
       run: make say-hello
